"""empty message

Revision ID: 40e8c166e169
Revises: 57b5497b11f4
Create Date: 2016-05-05 11:10:34.550826

"""

# revision identifiers, used by Alembic.
revision = '40e8c166e169'
down_revision = '57b5497b11f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
