"""empty message

Revision ID: 4c18d3f8a2a8
Revises: 4b9dadd5ab32
Create Date: 2016-05-03 15:23:18.065271

"""

# revision identifiers, used by Alembic.
revision = '4c18d3f8a2a8'
down_revision = '4b9dadd5ab32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
