"""empty message

Revision ID: 88fb416edbb0
Revises: e560e7faff29
Create Date: 2016-05-05 15:25:58.567460

"""

# revision identifiers, used by Alembic.
revision = '88fb416edbb0'
down_revision = 'e560e7faff29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
